### ISSUE TITLE
[Bug]: Causes TS2742 errors in unrelated files using Zod (1.2.6 regression)

### ISSUE THREAD

**Issue by andersk** [web-infra-dev/rspack#9816]
### System Info

```
  System:
    OS: Linux 6.14 cpe:/o:nixos:nixos:25.05 25.05 (Warbler)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 8.91 GB / 15.26 GB
    Container: Yes
    Shell: 5.2.37 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 22.14.0 - ~/.nix-profile/bin/node
    npm: 10.9.2 - ~/.nix-profile/bin/npm
    pnpm: 10.7.0 - ~/.nix-profile/bin/pnpm
    bun: 1.2.5 - ~/.nix-profile/bin/bun
  Browsers:
    Chromium: 134.0.6998.165
  npmPackages:
    @rspack/core: ^1.2.8 => 1.2.8 
```

### Details

In a project with the TypeScript [`composite`](https://www.typescriptlang.org/tsconfig/#composite) flag enabled, if I import `@rspack/core` in `rspack.config.ts`, this causes TypeScript errors about `./node_modules/@rspack/core/compiled/zod` in unrelated files that use (the real) `zod`.

This worked in `@rspack/core` 1.2.5 and broke in 1.2.6.

Deleting `node_modules/@rspack/core/compiled/zod/package.json` makes the error disappear.

**`rspack.config.ts`**

```ts
import type { Configuration } from "@rspack/core";

const config: Configuration = {};
export default config;
```

**`schema.ts`**

```ts
import { z } from "zod";

export const schema = z.string();
```

**`tsconfig.json`**

```ts
{
  "compilerOptions": {
    "composite": true,
    "moduleResolution": "bundler",
    "noEmit": true,
    "strict": true,
    "target": "ESNext"
  }
}
```

```console
$ pnpm exec tsc
schema.ts:3:14 - error TS2742: The inferred type of 'schema' cannot be named without a reference to './node_modules/@rspack/core/compiled/zod'. This is likely not portable. A type annotation is necessary.

3 export const schema = z.string();
               ~~~~~~


Found 1 error in schema.ts:3
```

### Reproduce link

https://gist.github.com/andersk/8c4dc22821406d9a6a23c6f967878633

### Reproduce Steps

```sh
git clone https://gist.github.com/andersk/8c4dc22821406d9a6a23c6f967878633 test
cd test
pnpm i
pnpm exec tsc
```

**Comment by chenjiahan** [comment]
This is actually a common problem with TypeScript, see https://github.com/microsoft/TypeScript/issues/42873

In Rspack 1.2.6, we have just updated zod to the latest ^3.24.2, see https://github.com/web-infra-dev/rspack/pull/9367. This may have triggered the issue with TS, but there is nothing Rspack can do about it.
