### ISSUE TITLE
[@rspack/plugin-node-polyfill@0.1.11] TypeError: console is not a function  

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#3187]
### System Info

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.11 => 0.1.11 
    @rspack/plugin-node-polyfill: ^0.1.11 => 0.1.11 

### Details

ref: https://github.com/web-infra-dev/rspack/pull/3154

When I upgraded the version to 0.1.11, the following error occurred.

![img_v2_4fab200d-e4c0-48cf-af9b-55c4867701dg](https://github.com/web-infra-dev/rspack/assets/16858738/ad76d371-2aea-41fa-b886-e2cbef6fbc08)

I found that there is a bug in the compiled code of this piece of [code](https://github.com/quilljs/quill/blob/develop/core/logger.ts) in this package.

A simple logger function like this:

```ts
export function debug(method: string, ...args: unknown[]) {
  console[method](...args);
}
```
And the compiled code :

<img width="605" alt="image" src="https://github.com/web-infra-dev/rspack/assets/16858738/2edbed61-60be-4a6e-890a-d6c6c92f2357">

### Reproduce link

https://github.com/KyrieLii/rspack-nodepolyfill-demo

### Reproduce Steps

1. pnpm install
2. pnpm run dev

**Comment by KyrieLii** [comment]
cc @hardfist ~

**Comment by hardfist** [comment]
just remove polyfill console, it's buggy
