### ISSUE TITLE
__webpack_require__ is conflicted when dependency is bundled

### ISSUE THREAD

**Issue by Thiry1** [web-infra-dev/rspack#3724]
### System Info

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 77.75 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.nodebrew/current/bin/node
    Yarn: 3.6.1 - ~/.nodebrew/current/bin/yarn
    npm: 9.5.1 - ~/.nodebrew/current/bin/npm
    pnpm: 8.6.6 - ~/.nodebrew/current/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5

### Details

After updating to v0.2.5, my app crashes at runtime.
```
/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:384
        __webpack_modules__[moduleId](module1, module1.exports, __webpack_require__);
                                     ^

TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:384:38)
    at Object.react (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:370:31)
    at __webpack_require__ (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:384:38)
    at ./src/index.js (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:364:49)
    at __webpack_require__ (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:384:38)
    at /Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:417:31
    at ../deps-lib/dist/main.js (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:419:3)
    at __webpack_require__ (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:439:36)
    at ./src/index.js (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:342:64)
    at __webpack_require__ (/Users/***/workspace/rspack-bug-repro/packages/app/dist/main.js:439:36)
```

I found the difference between v0.2.4 and v0.2.5.
v0.2.4
<img width="638" alt="スクリーンショット 2023-07-07 15 18 07" src="https://github.com/web-infra-dev/rspack/assets/6201376/5209d6ed-33d1-4f0b-98f5-b4d9721a64b4">
v0.2.5
<img width="727" alt="スクリーンショット 2023-07-07 15 18 28" src="https://github.com/web-infra-dev/rspack/assets/6201376/2bd8e6f2-a1f5-4ee2-b61c-5baf7f468125">

I guess `__webpack_require__` is conflicted when dependency is bundled.

### Reproduce link

https://github.com/Thiry1/rspack-bug-repro/tree/conflict-webpack-require

### Reproduce Steps

1. run `npm i && npm run build`
2. run `node ./packages/app/dist/main.js`
```[tasklist]
### Tasks
```

**Comment by underfin** [comment]
Sorry for this regression, it's caused by `__nest__webpack_require__` is not implemented at new version. The feature before it worked look like caused swc `hygine` is do it, but new version doesn't do it.  I will fixed it at next days.

**Comment by Thiry1** [comment]
@underfin Thank you for working on this.
I've tried on v0.2.6.
However, v0.2.6 seems to have the same problem.
__webpack_require__("react") is fine,  but __webpack_require__("../../node_modules/react/index.js")  gives the same error
https://github.com/Thiry1/rspack-bug-repro/commit/f1952614811831206beb24ea015ef80527806f14#diff-5dcccdc18ebc20562b4c193150510afc7ca0dbf2f5cdbcc81ddd4b21f0006e7bR333-L336

I've updated the reproduction code. Please take a look when you have time.
https://github.com/Thiry1/rspack-bug-repro/commit/f1952614811831206beb24ea015ef80527806f14

**Comment by Thiry1** [comment]
I found a workaround.
Set `output.libraryTarget` to `umd` instead of `commonjs2`.
