### ISSUE TITLE
[Bug]: CJS module tree shaking removes exports referenced via this, and (0, fn)() call pattern breaks this binding

### ISSUE THREAD

**Issue by cjnoname** [web-infra-dev/rspack#13801]
### System Info

```
System:
  OS: macOS 26.4
  CPU: arm64 Apple M4 Max
Binaries:
  Node: 25.8.1
  pnpm: 10.33.0
Packages:
  @rspack/core: 2.0.0
  @rspack/cli: 2.0.0
```

### Details

When bundling a CJS module whose exported functions reference sibling exports via `this` (e.g. `this.isSpecial()`), rspack 2.0.0 produces broken output due to **two compounding issues**:

#### Issue 1: Tree shaking removes exports that are only referenced via `this`

If `exports.isSpecial` is not directly imported by any other module but is called internally via `this.isSpecial()`, rspack's used-exports analysis marks it as unused and replaces the assignment with `__webpack_unused_export__`:

```js
// Source
exports.isSpecial = function isSpecial(name) { ... };

// Bundled output (WRONG)
__webpack_unused_export__ = function isSpecial(name) { ... };
```

The function is never attached to the `exports` object, so `this.isSpecial` is `undefined` at runtime.

#### Issue 2: `(0, fn)()` call pattern strips `this` context

Even if the export were preserved, the ESM consumer calls it via:

```js
(0, _lib_cjs__rspack_import_0.K)("admin")
```

The `(0, fn)()` comma-operator pattern evaluates to a bare function reference, so `this` becomes `undefined` (strict mode) instead of pointing to the `exports` object.

**Both issues must be fixed** for this pattern to work correctly. Issue 1 alone causes the crash; Issue 2 would cause the same crash even if Issue 1 were fixed.

### Root Cause

This appears to be related to [#13643](https://github.com/web-infra-dev/rspack/pull/13643) (`fix cjs export function tree shaking`) and [#13234](https://github.com/web-infra-dev/rspack/pull/13234) (`strictThisContextOnImports`). PR #13643 fixed CJS export tree shaking for the case where exports are consumed externally, but did not account for **intra-module `this`-based self-references** — a common CJS pattern where `exports.a` calls `this.b()` to invoke `exports.b`.

### Real-world Impact

This breaks `snowflake-sdk` (and likely other CJS packages using the same pattern). In `snowflake-sdk@2.4.0`, the file `dist/lib/authentication/authentication.js` uses exactly this pattern:

```js
exports.formAuthJSON = function formAuthJSON(authenticator, ...) {
    if (!this.isOktaAuth(authenticator)) { ... }   // ← calls sibling via this
};
exports.isOktaAuth = function isOktaAuth(authenticator) {
    return authenticator.toUpperCase().startsWith('HTTPS://');
};
```

`isOktaAuth` is never imported directly by other modules — it's only called internally via `this`. rspack tree-shakes it away, causing `TypeError: this.isOktaAuth is not a function` at runtime.

This worked in rspack 2.0.0-rc.1 and broke somewhere between rc.1 and 2.0.0 stable.

### Minimal Reproduction

**`lib.cjs`**:
```js
"use strict";

exports.greet = function greet(name) {
  if (this.isSpecial(name)) {
    return "Welcome back, " + name + "!";
  }
  return "Hello, " + name;
};

exports.isSpecial = function isSpecial(name) {
  return name === "admin";
};
```

**`index.js`**:
```js
import { greet } from "./lib.cjs";

const result = greet("admin");
console.log(result);
```

**`rspack.config.mjs`**:
```js
import { defineConfig } from "@rspack/cli";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  mode: "production",
  entry: "./index.js",
  target: "node",
  experiments: { outputModule: true },
  output: {
    filename: "bundle.mjs",
    path: path.join(__dirname, "dist"),
    chunkFormat: "module",
    library: { type: "module" },
    clean: true,
    module: true,
  },
  optimization: {
    minimize: false,
  },
});
```

**`package.json`**:
```json
{
  "type": "module",
  "scripts": { "build": "rspack build" },
  "devDependencies": {
    "@rspack/cli": "^2.0.0",
    "@rspack/core": "^2.0.0"
  }
}
```

### Reproduce Steps

```bash
pnpm install
pnpm run build
node dist/bundle.mjs
```

### Expected Behavior

```
Welcome back, admin!
```

### Actual Behavior

```
TypeError: Cannot read properties of undefined (reading 'isSpecial')
    at greet (file:///private/tmp/rspack-cjs-this-bug/dist/bundle.mjs:7:12)
```

Inspecting the bundled output reveals both issues:

```js
// Issue 1: isSpecial tree-shaken away
__webpack_unused_export__ = function isSpecial(name) {  // ← not attached to exports!
  return name === "admin";
};

// Issue 2: (0, fn)() strips this context
const result = (0,_lib_cjs__rspack_import_0.K)("admin");  // ← this === undefined
```

### Workaround

Manually re-bind the functions at runtime before the CJS module is consumed:

```js
const mod = require("./lib.cjs");
if (typeof mod.isSpecial !== "function") {
  // restore tree-shaken export
}
mod.greet = (...args) => mod.greet.apply(mod, args);  // fix this binding
```

### Additional Context

- Previously reported a related (but different) bug: [#13070](https://github.com/web-infra-dev/rspack/issues/13070) — optional chaining stripped in CJS self-reference. That was fixed in beta.4 via [#13132](https://github.com/web-infra-dev/rspack/pull/13132).
- The current bug is a **separate regression** introduced after rc.1, likely by the `strictThisContextOnImports` changes ([#13234](https://github.com/web-infra-dev/rspack/pull/13234)) and/or the CJS tree shaking fix ([#13643](https://github.com/web-infra-dev/rspack/pull/13643)) not fully covering intra-module `this` references.

**Comment by ahabhgk** [comment]
This is by design, checkout [strictThisContextOnImports](https://rspack.rs/config/module#moduleparserjavascriptstrictthiscontextonimports).

For the snowflake-sdk case I suggest add this module rule to your rspack.config.js:

```js
{
  test: /snowflake-sdk[\\\/]lib[\\\/]connection[\\\/]connection\.js/, // snowflake-sdk/lib/connection/connection.js is the module that importing authentication.js
  parser: {
    strictThisContextOnImports: true,
  }
}
```

This pattern is very uncommon even for cjs, if more people encounter this problem in the future, we will make some adjustments.

**Comment by cjnoname** [comment]
Thanks for the suggestion. I tried adding `strictThisContextOnImports: true` but it does not fix the issue.

**What I tested:**

```js
// rspack.config.mjs
module: {
  rules: [
    {
      test: /index\.js/,
      parser: {
        strictThisContextOnImports: true,
      },
    },
  ],
},
```

**Result:** Same error. The bundled output is identical — both problems remain:

1. `isSpecial` is still tree-shaken to `__webpack_unused_export__` (not attached to `exports`)
2. The call is still `(0, fn)()` pattern (stripping `this`)

```js
// dist/bundle.mjs (with strictThisContextOnImports: true)

// Issue 1 still present: isSpecial not on exports
__webpack_unused_export__ = function isSpecial(name) {
  return name === "admin";
};

// Issue 2 still present: (0, fn)() strips this
const result = (0,_lib_cjs__rspack_import_0.K)("admin");
```

The core problem is that the used-exports analysis does not track `this.xxx()` references within the same CJS module. Even if we fix the `this` binding via `strictThisContextOnImports`, the export is already gone — `this.isSpecial` would still be `undefined` because it was never attached to the `exports` object.

**Comment by ahabhgk** [comment]
In your case you are using `import { greet } from "./lib.cjs"; greet();`, `this` is undefined, you can varify that by `node ./index.js`, which will also report `TypeError: Cannot read properties of undefined (reading 'isSpecial')`, so the bundle output is correct

If you want `this` bind to the cjs module, you need to use `import * as lib from "./lib.cjs"; lib.greet()`, which will make `strictThisContextOnImports` effect, to make the bundle output correct

Same for cjs require:

- `const { greet } = require("./lib.cjs"); greet()`, `this` is undefined
- `const lib = require("./lib.cjs"); lib.greet()`, `this` is bind to cjs module, `strictThisContextOnImports` effect

**Comment by cjnoname** [comment]
You're right that `import { greet } from "./lib.cjs"; greet()` has `this === undefined` in native Node.js — I acknowledge that part of the reproduction was incorrect.

However, the real-world issue (snowflake-sdk) is **not** about named vs namespace imports. Inside snowflake-sdk, the consumer is CJS requiring another CJS module:

```js
// snowflake-sdk/dist/lib/connection/connection.js
const Authenticator = require('../authentication/authentication');
// ...
body = Authenticator.formAuthJSON(...);  // this === Authenticator (exports object) ✓
```

This is already namespace-style — `this` binding is correct. The problem is purely **tree shaking**: `exports.isOktaAuth` is only referenced via `this.isOktaAuth()` inside `formAuthJSON` and `getAuthenticator`, never imported directly by any other module. So rspack marks it unused and replaces it with `__webpack_unused_export__`.

I tested adding `strictThisContextOnImports: true` on the consumer files (`connection.js` and `sf.js`):

```js
{
  test: /snowflake-sdk[\\/]dist[\\/]lib[\\/](connection[\\/]connection|services[\\/]sf)\.js$/,
  parser: { strictThisContextOnImports: true }
}
```

**Result: `isOktaAuth` is still tree-shaken away.** The function body (containing `HTTPS://`) is completely absent from the bundle. `strictThisContextOnImports` does not prevent the used-exports analysis from marking `isOktaAuth` as unused.

The core issue remains: when a CJS module uses `exports.a = function() { this.b() }`, rspack's used-exports analysis does not recognize that `exports.b` is referenced via `this` and incorrectly removes it.

**Comment by ahabhgk** [comment]
With `strictThisContextOnImports` enabled it should prevent the tree shaking, I can't simply reproduce it with snowflake-sdk at local, can you provide a reproduction?

**Comment by cjnoname** [comment]
Hi @ahabhgk, I owe you an apology — my earlier replies were wrong. I was using an AI assistant to help debug this, and it led me down the wrong path with incorrect test results.

You were absolutely right: `strictThisContextOnImports` does fix this when applied correctly. The issue in our codebase turned out to be in our shared Rspack config where the rule had three bugs:

1. The regex was missing `dist/` in the path (`snowflake-sdk/lib/...` instead of `snowflake-sdk/dist/lib/...`)
2. It was only targeting `connection.js` but missed `sf.js` which also requires the authentication module
3. The parser option was nested incorrectly as `parser: { javascript: { strictThisContextOnImports: true } }` instead of `parser: { strictThisContextOnImports: true }`

Once all three were fixed, everything works perfectly — `isOktaAuth` is preserved in the bundle and `this` binding is correct.

Thank you for your patience and for pointing us in the right direction. Sorry for the noise — closing this now.
