### ISSUE TITLE
[Bug]: TS Errors When Running With `skipLibCheck: false`

### ISSUE THREAD

**Issue by adrians5j** [web-infra-dev/rspack#9154]
### System Info

  System:
    OS: macOS 12.7.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.70 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.18.2 - /usr/local/bin/node
    Yarn: 4.6.0 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 132.1.74.48
    Safari: 15.6.1

### Details

> [!NOTE]  
> This issue is similar to the one I described [here](https://github.com/web-infra-dev/rspack/issues/8937). This time just have a different TS error that's occurring.

We're building our project which has `skipLibCheck:false` in one of our build steps.

In that process, build fails with the following TS errors:

```
Error: [FAILED] ../../node_modules/@rspack/core/compiled/@swc/types/index.d.ts(1,29): error TS2307: Cannot find module './assumptions' or its corresponding type declarations.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2378,57): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2378,92): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2398,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2409,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2425,57): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2425,92): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2439,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2447,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2518,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2540,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2561,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2583,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2709,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2731,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2857,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(2879,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(3029,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(3051,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts([363](https://github.com/webiny/webiny-js/actions/runs/13135499432/job/36649881159#step:6:364)4,31): error TS2315: Type 'Buffer' is not generic.
Error: [FAILED] ../../node_modules/@rspack/core/dist/config/zod.d.ts(3656,31): error TS2315: Type 'Buffer' is not generic.
```

Dug into the code a bit, and for example, for the first TS2307 error, I can see it:

![Image](https://github.com/user-attachments/assets/2b77391f-26f8-4715-81f4-5e7d749348a8)

### Reproduce Steps

In our repo, we've run our build process with the skipLibCheck: false in our TS config. With this setting, we can see the above errors.

**Comment by DavidReinberger** [comment]
Running in to the same issue after upgrading to 1.2.2.

**Comment by CPunisher** [comment]
maybe ci is needed

**Comment by inottn** [comment]
What version of `@types/node` are you relying on? In version 20.17.10, the type `Buffer` is a generic type.

**Comment by adrians5j** [comment]
When I do `yarn why @types/node`, I actually get that exact version. 🤷🏻

**Comment by DavidReinberger** [comment]
The issue is typescript version. We are using `5.5.4` and if you take a look at the `@types/node` in your `node_modules` there is a folder called `ts5.6` which contain this line `These definitions support Node.js and TypeScript 4.9 through 5.6` and Buffer is a non-generic type. If I manually upgrade typescript to `5.7.3` it works as expected.

**Comment by adrians5j** [comment]
Thanks @DavidReinberger, will give it a try.

**Comment by adrians5j** [comment]
Thanks @DavidReinberger!

**Comment by chenjiahan** [comment]
We will close this issue as it can be resolved by upgrading TypeScript version.

**Comment by chenjiahan** [comment]
See the above comment: https://github.com/web-infra-dev/rspack/issues/9154#issuecomment-2647579073
