### PR TITLE
fix: module graph incorrect when delete or create file

### PR DESCRIPTION
**Pull request by jerrykingxyz**
## Summary

This PR fix the module graph incorrect when delete or create file. There are some summary:

* Add parent module to `force_build_module` when module factorize failed instead of add deps to `force_build_deps`. if the module is entry module, we should still add deps to `force_build_deps`, because of it no parent module.
* Deleting the file should not only mark the affected module as `force_build_module` but also add its parent module to `force_build_module`

We can see a simply example:
``` js
// index.js
import a form "./a" // <-- HarmonyImportSideEffectDependency
console.log(a) // <-- HarmonyImportSpecifierDependency
```
the `index.js` have two deps `HarmonyImportSideEffectDependency` and `HarmonyImportSpecifierDependency` . 

If we don't have `a.js` and create it, we should not only create the module for `a.js` in HMR but also recreate `index.js` to make sure all dependencies are correct
if we have `a.js` and delete it, we should not only delete the module for `a.js` in HMR but also recreate `index.js` to make sure all dependencies are correct

## Test Plan

* enable missing file e2e test

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by h-a-n-a** [comment]
Summary looks good to me. 

To be specific, missing dependencies will interfere the code generation of parent modules. 

To demonstrate the issue even further, here's the result if module "./a" is not exist:
```
// index.js
Object(function webpackMissingModule() { var e = new Error("Cannot find module './a'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
console.log(Object(function webpackMissingModule() { var e = new Error("Cannot find module './a'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());)
```

In order to recover from the missing dependency. './index.js' should be generated again. This is a breaking change introduced by https://github.com/web-infra-dev/rspack/pull/5124.

**Comment by h-a-n-a** [comment]
I will approve this PR, but I would also like to see if there's any performance regression in this case change.
The current benchmark suites are not located in this repo, causing adding benchmark case for current PR is not as much easy as it used to be ;-(

**Review by h-a-n-a — APPROVED** [review]

**Comment by jerrykingxyz** [comment]
!bench
