### ISSUE TITLE
rspack@1.7: `compiler.webpack` is not a function

### ISSUE THREAD

**Issue by axetroy** [web-infra-dev/rspack#12612]
`compiler.webpack` has been remove after upgrade to rspack 1.7.x from 1.6.0

I've searched through release announcements

but couldn't find anything related. I think it was removed accidentally?

before rspack 1.6.0

```js
typeof compiler.webpack // 'function'
typeof compiler.rspack // 'function'
```

after rspack 1.7.0

```js
typeof compiler.webpack // 'object'
typeof compiler.rspack // 'object'
```

**Comment by chenjiahan** [comment]
Related: https://github.com/web-infra-dev/rspack/pull/12371/files#diff-5eba14dafadd5b7ee447411919692ad06f841b6b93770e131cc6b364771f68b5R249-R257

@LingyuCoder cc

**Comment by axetroy** [comment]
> Related: [#12371 (files)](https://github.com/web-infra-dev/rspack/pull/12371/files#diff-5eba14dafadd5b7ee447411919692ad06f841b6b93770e131cc6b364771f68b5R249-R257)
> 
> [@LingyuCoder](https://github.com/LingyuCoder) cc

it's a BREAKING CHANGE and it was not declared in the release announcements.

**Comment by chenjiahan** [comment]
It seems like a bug and can be fixed.
